# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_created', models.DateTimeField(blank=True, db_column='_created', null=True)),
                ('field_updated', models.DateTimeField(blank=True, db_column='_updated', null=True)),
                ('field_etag', models.CharField(blank=True, db_column='_etag', max_length=40, null=True)),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('paired', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_created', models.DateTimeField(blank=True, db_column='_created', null=True)),
                ('field_updated', models.DateTimeField(blank=True, db_column='_updated', null=True)),
                ('field_etag', models.CharField(blank=True, db_column='_etag', max_length=40, null=True)),
                ('pid', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Input',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_created', models.DateTimeField(blank=True, db_column='_created', null=True)),
                ('field_updated', models.DateTimeField(blank=True, db_column='_updated', null=True)),
                ('field_etag', models.CharField(blank=True, db_column='_etag', max_length=40, null=True)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('salt', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
